User.create(email: "J@gmail.com", password: "password", first_name: "James", last_name: "Ma", mobile: "123456")
User.create(email: "K@gmail.com", password: "password", first_name: "Kuan", last_name: "Lee", mobile: "654321")
Category.create(name: "music")
Subscription.create(name: "Netflix", payment_amount: 6, reminder: "time to go", user_id: 1, category_id: 1)
Subscription.create(name: "Spotify", payment_amount: 12, reminder: "right now", user_id: 2, category_id: 1)
